/* ==================================================================
   BUILD THE DEPLOY BUNDLE
   ------------------------------------------------------------------
   Produces `deploy/` — a self-contained folder you can upload to GitHub
   and hand to Koyeb. Three files, one dependency.

   Why a bundle instead of deploying the repo as-is?
     - The repo root's package.json has no `start` that runs the server,
       and its dependencies live in server/node_modules.
     - Koyeb's Node buildpack wants package.json at the root of what it
       builds, and runs `npm install` then `npm start`.
     - A beginner should be able to look at three files and understand
       every one of them.

   The bundle is GENERATED. Never edit deploy/ by hand — edit
   server/index.js or shared/sim.js and re-run:

       npm run deploy:build

   `npm run deploy:check` fails if deploy/ has drifted from the source,
   so a stale bundle can't quietly ship.
   ================================================================== */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUT = path.join(ROOT, "deploy");

const serverSrc = fs.readFileSync(path.join(ROOT, "server", "index.js"), "utf8");
const simSrc = fs.readFileSync(path.join(ROOT, "shared", "sim.js"), "utf8");

// In the repo the server imports ../shared/sim.js. In the bundle the sim
// sits one level down, so the path changes to ./shared/sim.js.
const OLD = 'from "../shared/sim.js"';
const NEW = 'from "./shared/sim.js"';
if (!serverSrc.includes(OLD)) {
  console.error(`FAIL: expected ${OLD} in server/index.js — did the import move?`);
  process.exit(1);
}
const bundled = serverSrc.replace(OLD, NEW);

const pkg = {
  name: "cart-io-server",
  version: "0.2.0",
  private: true,
  type: "module",
  description: "Cart.io authoritative game server",
  main: "index.js",
  scripts: { start: "node index.js" },
  // Koyeb's free instance runs a recent Node; >=18 is what we test against.
  engines: { node: ">=18" },
  dependencies: { ws: "^8.18.0" },
};

const readme = `# Cart.io — game server

Self-contained deploy bundle. Generated by \`npm run deploy:build\` from
\`server/index.js\` + \`shared/sim.js\`. Do not edit by hand.

- \`index.js\` — the authoritative game server (WebSocket + HTTP health check)
- \`shared/sim.js\` — the rules. Server and browser run the same file.
- \`package.json\` — one dependency: \`ws\`

## Run it locally

\`\`\`bash
npm install
npm start          # listens on 0.0.0.0:2567
\`\`\`

## Health check

\`GET /health\` returns JSON \`{"ok":true,...}\`. Koyeb uses this to decide
whether the service is alive — a bare WebSocket server answers \`426\` to
plain HTTP and gets restarted in a loop.

## Environment

| Var | Default | Note |
|---|---|---|
| \`PORT\` | \`2567\` | Koyeb sets this itself. Never hardcode a port. |
| \`HOST\` | \`0.0.0.0\` | Must stay \`0.0.0.0\`, never \`127.0.0.1\`. |
`;

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, "shared"), { recursive: true });
fs.writeFileSync(path.join(OUT, "index.js"), bundled);
fs.writeFileSync(path.join(OUT, "shared", "sim.js"), simSrc);
fs.writeFileSync(path.join(OUT, "package.json"), JSON.stringify(pkg, null, 2) + "\n");
fs.writeFileSync(path.join(OUT, "README.md"), readme);
// Written here, not by hand: deploy/ is wiped and rebuilt every time, so a
// hand-made .gitignore silently vanishes on the next build. Koyeb runs
// `npm install` itself — node_modules must never be uploaded.
fs.writeFileSync(path.join(OUT, ".gitignore"), "node_modules/\nnpm-debug.log\n");

const size = fs.statSync(path.join(OUT, "index.js")).size + fs.statSync(path.join(OUT, "shared", "sim.js")).size;
console.log("deploy/ built:");
console.log(`  index.js         ${(fs.statSync(path.join(OUT, "index.js")).size / 1024).toFixed(1)} KB`);
console.log(`  shared/sim.js    ${(fs.statSync(path.join(OUT, "shared", "sim.js")).size / 1024).toFixed(1)} KB`);
console.log(`  package.json     1 dependency (ws)`);
console.log(`  total source     ${(size / 1024).toFixed(1)} KB`);
